import "./globals.css";

import { Poppins } from "next/font/google";

const poppins = Poppins({ subsets: ["latin"], weight: ["400", "500"] });

export const metadata = {
  title: "itexpert120's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className="scroll-smooth dark:text-[#A7A7A7] dark:bg-[#191919]"
    >
      <body className={poppins.className}>{children}</body>
    </html>
  );
}
